# scikit-learn 
## (Data Preprocessing with scikit-learn)

### Standardizing Data

In [ ]:
# Standard data format 
#     x−μ
# z= ------
#     σ


In [ ]:
# NumPy and scikit-learn 


# predefined pizza data
# Newline to separate print statements
import numpy as np
pizza_data = np.array([
    [12, 300, 15],
    [14, 350, 18],
    [16, 400, 20]
])

print('{}\n'.format(repr(pizza_data)))

from sklearn.preprocessing import scale
# Standardizing each column of pizza_data
col_standardized = scale(pizza_data)
print('{}\n'.format(repr(col_standardized)))

# Column means (rounded to nearest thousandth)
col_means = col_standardized.mean(axis=0).round(decimals=3)
print('{}\n'.format(repr(col_means)))

# Column standard deviations
col_stds = col_standardized.std(axis=0)
print('{}\n'.format(repr(col_stds)))

array([[ 12, 300,  15],
       [ 14, 350,  18],
       [ 16, 400,  20]])

array([[-1.22474487, -1.22474487, -1.29777137],
       [ 0.        ,  0.        ,  0.16222142],
       [ 1.22474487,  1.22474487,  1.13554995]])

array([ 0.,  0., -0.])

array([1., 1., 1.])



### Data Range 

In [ ]:
# # Range scaling

# The formula for scaling based on a range is a two-step process. For a given data value, x, we first compute the proportion of the value with respect to the min and max of the data dmin and dmax, respectively).
# #  To implement the formula:
 
# # [ x_{\text{prop}} = \frac{x - d_{\text{min}}}{d_{\text{max}} - d_{\text{min}}} ]
# # (i.e. dmax ≠ dmin).

# We then use the proportion of the value to scale to the specified range, [rmin, rmax]. The formula below calculates the new scaled value, xscale.

# [ x_{\text{scale}} = x_{\text{prop}} \cdot (r_{\text{max}} - r_{\text{min}}) + r_{\text{min}} ]


In [7]:
# Range compression in scikit-learn

# predefined data

import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Define data as a NumPy array
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('{}\n'.format(repr(data)))

from sklearn.preprocessing import MinMaxScaler
default_scaler = MinMaxScaler() # the default range is [0,1]
transformed = default_scaler.fit_transform(data)
print('{}\n'.format(repr(transformed)))

custom_scaler = MinMaxScaler(feature_range=(-2, 3))
transformed = custom_scaler.fit_transform(data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

array([[-2. , -2. , -2. ],
       [ 0.5,  0.5,  0.5],
       [ 3. ,  3. ,  3. ]])



In [8]:
# fit and transform functions 


# predefined new_data
new_data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('{}\n'.format(repr(new_data)))

from sklearn.preprocessing import MinMaxScaler
default_scaler = MinMaxScaler() # the default range is [0,1]
transformed = default_scaler.fit_transform(new_data)
print('{}\n'.format(repr(transformed)))

default_scaler = MinMaxScaler()  # new instance
default_scaler.fit(data)  # different data value fit
transformed = default_scaler.transform(new_data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])



### Normalizing Data 

In [2]:
# L2 normalization 


import numpy as np
# predefined data
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('{}\n'.format(repr(data)))

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
transformed = normalizer.fit_transform(data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.50257071, 0.57436653, 0.64616234]])



### Data Imputation

In [4]:
# Data imputation methods 

# predefined data
print('{}\n'.format(repr(data)))

from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer()
transformed = imp_mean.fit_transform(data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])



In [3]:
#   using SimpleImputer. 

# predefined data
print('{}\n'.format(repr(data)))

from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(strategy='median')
transformed = imp_median.fit_transform(data)
print('{}\n'.format(repr(transformed)))

imp_frequent = SimpleImputer(strategy='most_frequent')
transformed = imp_frequent.fit_transform(data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])



In [6]:
# predefined data
print('{}\n'.format(repr(data)))

from sklearn.impute import SimpleImputer
imp_constant = SimpleImputer(strategy='constant',
                             fill_value=-1)
transformed = imp_constant.fit_transform(data)
print('{}\n'.format(repr(transformed)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])



### (PCA)  principal component analysis  

In [7]:
#  PCA in scikit-learn 


# predefined data
print('{}\n'.format(repr(data)))

from sklearn.decomposition import PCA
pca_obj = PCA() # The value of n_component will be 4. As m is 5 and default is always m-1
pc = pca_obj.fit_transform(data).round(3)
print('{}\n'.format(repr(pc)))

pca_obj = PCA(n_components=3)
pc = pca_obj.fit_transform(data).round(3)
print('{}\n'.format(repr(pc)))

pca_obj = PCA(n_components=2)
pc = pca_obj.fit_transform(data).round(3)
print('{}\n'.format(repr(pc)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[-5.196, -0.   ,  0.   ],
       [ 0.   , -0.   ,  0.   ],
       [ 5.196, -0.   ,  0.   ]])

array([[-5.196, -0.   ,  0.   ],
       [ 0.   , -0.   ,  0.   ],
       [ 5.196, -0.   ,  0.   ]])

array([[-5.196, -0.   ],
       [ 0.   , -0.   ],
       [ 5.196, -0.   ]])



### Labeled Data 

In [8]:
# Class labels 

from sklearn.datasets import load_breast_cancer
bc = load_breast_cancer()
print('{}\n'.format(repr(bc.data)))
print('Data shape: {}\n'.format(bc.data.shape))

# Class labels
print('{}\n'.format(repr(bc.target)))
print('Labels shape: {}\n'.format(bc.target.shape))

# Label names
print('{}\n'.format(list(bc.target_names)))

malignant = bc.data[bc.target == 0]
print('Malignant shape: {}\n'.format(malignant.shape))

benign = bc.data[bc.target == 1]
print('Benign shape: {}\n'.format(benign.shape))



array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

Data shape: (569, 30)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1